FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main

# Ajouter l’architecture arm64 avant d’installer le paquet
ARG CROSS_DEB_ARCH
RUN dpkg --add-architecture ${CROSS_DEB_ARCH} && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        libudev-dev:${CROSS_DEB_ARCH} pkg-config libasound2-dev:${CROSS_DEB_ARCH} && \
    rm -rf /var/lib/apt/lists/*

