pub mod visualizer_app;
mod visualizer_service;
mod smooth_size_chrc;
mod gain_chrc;
mod fps_chrc;
mod fft_size_chrc;
pub mod registration;
mod led_count_chrc;
mod leds_buffer_chrc;
mod leds_buffer2_chrc;