pub mod visualizer_app;
mod service_visualizer;
mod chrc_smooth_size;
mod chrc_gain;
mod chrc_fps;
mod chrc_fft_size;
pub mod registration;
mod chrc_led_count;
mod chrc_leds_buffer;
mod chrc_leds_buffer2;
mod chrc_frequencies;
mod chrc_gains;
mod chrc_brightness;
mod chrc_color;
mod chrc_animation_mode;
mod chrc_display_mode;
mod chrc_skew;
mod chrc_presets_list;
mod chrc_presets_select;
mod chrc_presets_read;
mod chrc_presets_save;
mod chrc_presets_activate;
mod chrc_presets_read_activated_index;
mod chrc_presets_delete;
mod chrc_read_settings_as_preset;